/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PA0 */

	// Set pin direction to input
	PA0_set_dir(PORT_DIR_IN);

	PA0_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	/* PORT setting on PA2 */

	// Set pin direction to output

	BUZZER_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	BUZZER_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA3 */

	// Set pin direction to output

	W0_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W0_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA4 */

	// Set pin direction to output

	W1_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W1_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA5 */

	// Set pin direction to output

	W2_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W2_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA6 */

	// Set pin direction to output

	W3_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W3_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA7 */

	// Set pin direction to output

	TXEN_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	TXEN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC0 */

	// Set pin direction to output

	TX_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	TX_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC1 */

	// Set pin direction to input
	RX_set_dir(PORT_DIR_IN);

	RX_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	/* PORT setting on PC2 */

	/* PORT setting on PC3 */

	/* PORT setting on PD0 */

	// Set pin direction to output

	R0_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R0_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD1 */

	// Set pin direction to output

	G0_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G0_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD2 */

	// Set pin direction to output

	B0_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B0_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD3 */

	// Set pin direction to output

	R1_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R1_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD4 */

	// Set pin direction to output

	G1_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G1_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD5 */

	// Set pin direction to output

	B1_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B1_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD6 */

	/* PORT setting on PD7 */

	/* PORT setting on PF0 */

	// Set pin direction to output

	R2_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R2_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF1 */

	// Set pin direction to output

	G2_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G2_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF2 */

	// Set pin direction to output

	B2_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B2_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF3 */

	// Set pin direction to output

	R3_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R3_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF4 */

	// Set pin direction to output

	G3_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G3_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF5 */

	// Set pin direction to output

	B3_MCU_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B3_MCU_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF6 */

	// Set pin direction to input
	RESET_set_dir(PORT_DIR_IN);

	RESET_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	CLKCTRL_init();

	CPUINT_init();

	SLPCTRL_init();

	BOD_init();
}
